<?php

namespace Database\Seeders;

use App\Models\Cluster;
use Illuminate\Database\Seeder;

class ClusterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $clusters = [
            ['id' => 1, 'badan_usaha_id' => 1, 'division_id' => 1, 'region_id' => 1, 'name' => 'CSW1'],
            ['id' => 2, 'badan_usaha_id' => 1, 'division_id' => 1, 'region_id' => 1, 'name' => 'CSW2'],
            ['id' => 3, 'badan_usaha_id' => 1, 'division_id' => 1, 'region_id' => 1, 'name' => 'CSW3'],
            ['id' => 4, 'badan_usaha_id' => 1, 'division_id' => 1, 'region_id' => 1, 'name' => 'CSW4'],
            ['id' => 5, 'badan_usaha_id' => 1, 'division_id' => 1, 'region_id' => 1, 'name' => 'CSW5'],
            ['id' => 6, 'badan_usaha_id' => 1, 'division_id' => 1, 'region_id' => 1, 'name' => 'CSW6'],
            ['id' => 17, 'badan_usaha_id' => 1, 'division_id' => 1, 'region_id' => 3, 'name' => 'CNW1'],
            ['id' => 18, 'badan_usaha_id' => 1, 'division_id' => 1, 'region_id' => 3, 'name' => 'CNW2'],
            ['id' => 19, 'badan_usaha_id' => 1, 'division_id' => 1, 'region_id' => 3, 'name' => 'CNW3'],
            ['id' => 20, 'badan_usaha_id' => 1, 'division_id' => 1, 'region_id' => 3, 'name' => 'CNW4'],
            ['id' => 21, 'badan_usaha_id' => 1, 'division_id' => 1, 'region_id' => 3, 'name' => 'CNW5'],
            ['id' => 22, 'badan_usaha_id' => 1, 'division_id' => 1, 'region_id' => 6, 'name' => 'CNC1'],
            ['id' => 23, 'badan_usaha_id' => 1, 'division_id' => 1, 'region_id' => 6, 'name' => 'CNC2'],
            ['id' => 24, 'badan_usaha_id' => 1, 'division_id' => 1, 'region_id' => 6, 'name' => 'CNC3'],
            ['id' => 25, 'badan_usaha_id' => 1, 'division_id' => 1, 'region_id' => 6, 'name' => 'CNC4'],
            ['id' => 26, 'badan_usaha_id' => 1, 'division_id' => 1, 'region_id' => 6, 'name' => 'CNC5'],
            ['id' => 49, 'badan_usaha_id' => 2, 'division_id' => 3, 'region_id' => 5, 'name' => 'CWT1'],
            ['id' => 50, 'badan_usaha_id' => 2, 'division_id' => 3, 'region_id' => 5, 'name' => 'CWT2'],
            ['id' => 51, 'badan_usaha_id' => 2, 'division_id' => 3, 'region_id' => 5, 'name' => 'CWT3'],
            ['id' => 52, 'badan_usaha_id' => 2, 'division_id' => 3, 'region_id' => 8, 'name' => 'CJT1'],
            ['id' => 53, 'badan_usaha_id' => 2, 'division_id' => 3, 'region_id' => 8, 'name' => 'CJT2'],
            ['id' => 60, 'badan_usaha_id' => 1, 'division_id' => 1, 'region_id' => 9, 'name' => 'CSC1'],
            ['id' => 61, 'badan_usaha_id' => 1, 'division_id' => 1, 'region_id' => 9, 'name' => 'CSC2'],
            ['id' => 62, 'badan_usaha_id' => 1, 'division_id' => 1, 'region_id' => 9, 'name' => 'CSC3'],
            ['id' => 63, 'badan_usaha_id' => 1, 'division_id' => 1, 'region_id' => 9, 'name' => 'CSC4'],
            ['id' => 64, 'badan_usaha_id' => 1, 'division_id' => 1, 'region_id' => 9, 'name' => 'CSC5'],
            ['id' => 68, 'badan_usaha_id' => 2, 'division_id' => 3, 'region_id' => 11, 'name' => 'CJT3'],
            ['id' => 69, 'badan_usaha_id' => 2, 'division_id' => 3, 'region_id' => 11, 'name' => 'CJT4'],
            ['id' => 76, 'badan_usaha_id' => 3, 'division_id' => 5, 'region_id' => 17, 'name' => '-'],
            ['id' => 77, 'badan_usaha_id' => 1, 'division_id' => 1, 'region_id' => 18, 'name' => 'JBO'],
            ['id' => 80, 'badan_usaha_id' => 2, 'division_id' => 3, 'region_id' => 20, 'name' => 'JBOT'],
            ['id' => 94, 'badan_usaha_id' => 1, 'division_id' => 1, 'region_id' => 3, 'name' => 'CNW6'],
            ['id' => 183, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 28, 'name' => 'BOGOR1'],
            ['id' => 184, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 28, 'name' => 'BOGOR2'],
            ['id' => 185, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 28, 'name' => 'DEPOK1'],
            ['id' => 186, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 29, 'name' => 'BEKASI1'],
            ['id' => 187, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 29, 'name' => 'BEKASI2'],
            ['id' => 188, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 29, 'name' => 'BEKASI3'],
            ['id' => 189, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 29, 'name' => 'CIKARANG'],
            ['id' => 190, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 30, 'name' => 'BANDUNGKOTA'],
            ['id' => 191, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 30, 'name' => 'BANDUNGTIMUR'],
            ['id' => 192, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 30, 'name' => 'CIMAHI&BANDUNGUTARA'],
            ['id' => 193, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 31, 'name' => 'TASIKMALAYA'],
            ['id' => 194, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 31, 'name' => 'MAJALENGKA'],
            ['id' => 195, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 31, 'name' => 'INDRAMAYU'],
            ['id' => 196, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 32, 'name' => 'SEMARANGKUDUS'],
            ['id' => 197, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 30, 'name' => 'BANDUNGBARAT'],
            ['id' => 198, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 28, 'name' => 'BOGOR3'],
            ['id' => 199, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 33, 'name' => 'SURABAYA'],
            ['id' => 200, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 33, 'name' => 'MADIUN'],
            ['id' => 201, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 33, 'name' => 'MALANG'],
            ['id' => 202, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 33, 'name' => 'SIDOARJO'],
            ['id' => 203, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 33, 'name' => 'GRESIK'],
            ['id' => 204, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 33, 'name' => 'MOJOKERTO'],
            ['id' => 205, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 30, 'name' => 'BANDUNGSELATAN'],
            ['id' => 206, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 31, 'name' => 'SUBANGPURWAKARTA'],
            ['id' => 207, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 41, 'name' => 'SUKABUMI'],
            ['id' => 208, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 41, 'name' => 'CIANJUR'],
            ['id' => 209, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 41, 'name' => 'GARUTSUMEDANG'],
            ['id' => 210, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 41, 'name' => 'CIAMISBANJARPANGANDARAN'],
            ['id' => 211, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 41, 'name' => 'CIREBONKUNINGAN'],
            ['id' => 212, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 28, 'name' => 'DEPOK2'],
            ['id' => 213, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 42, 'name' => 'LOMBOK'],
            ['id' => 214, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 32, 'name' => 'JATENG'],
            ['id' => 215, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 33, 'name' => 'JATIM'],
            ['id' => 216, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 33, 'name' => 'JEMBER'],
            ['id' => 217, 'badan_usaha_id' => 2, 'division_id' => 6, 'region_id' => 43, 'name' => 'BANDUNG&CIMAHI'],
            ['id' => 218, 'badan_usaha_id' => 2, 'division_id' => 6, 'region_id' => 44, 'name' => 'PURWAKARTA'],
            ['id' => 219, 'badan_usaha_id' => 2, 'division_id' => 6, 'region_id' => 44, 'name' => 'CIKAMPEK'],
            ['id' => 220, 'badan_usaha_id' => 2, 'division_id' => 6, 'region_id' => 44, 'name' => 'KARAWANG-SD'],
            ['id' => 221, 'badan_usaha_id' => 2, 'division_id' => 6, 'region_id' => 44, 'name' => 'SUBANG'],
            ['id' => 222, 'badan_usaha_id' => 2, 'division_id' => 6, 'region_id' => 44, 'name' => 'KALIJATI'],
            ['id' => 223, 'badan_usaha_id' => 2, 'division_id' => 6, 'region_id' => 44, 'name' => 'PAMANUKAN'],
            ['id' => 224, 'badan_usaha_id' => 2, 'division_id' => 6, 'region_id' => 45, 'name' => 'CIREBON'],
            ['id' => 225, 'badan_usaha_id' => 2, 'division_id' => 6, 'region_id' => 45, 'name' => 'KUNINGAN-SD'],
            ['id' => 228, 'badan_usaha_id' => 2, 'division_id' => 6, 'region_id' => 45, 'name' => 'INDRAMAYU-SD'],
            ['id' => 230, 'badan_usaha_id' => 2, 'division_id' => 6, 'region_id' => 45, 'name' => 'MAJALENGKA-SD'],
            ['id' => 231, 'badan_usaha_id' => 2, 'division_id' => 6, 'region_id' => 46, 'name' => 'GARUT'],
            ['id' => 232, 'badan_usaha_id' => 2, 'division_id' => 6, 'region_id' => 46, 'name' => 'TASIK'],
            ['id' => 233, 'badan_usaha_id' => 2, 'division_id' => 6, 'region_id' => 46, 'name' => 'PANGANDARAN'],
            ['id' => 234, 'badan_usaha_id' => 2, 'division_id' => 6, 'region_id' => 46, 'name' => 'SUMEDANG'],
            ['id' => 235, 'badan_usaha_id' => 2, 'division_id' => 6, 'region_id' => 47, 'name' => 'BEKASI'],
            ['id' => 237, 'badan_usaha_id' => 2, 'division_id' => 6, 'region_id' => 47, 'name' => 'CIKARANG-SD'],
            ['id' => 238, 'badan_usaha_id' => 2, 'division_id' => 6, 'region_id' => 48, 'name' => 'BOGOR'],
            ['id' => 239, 'badan_usaha_id' => 2, 'division_id' => 6, 'region_id' => 48, 'name' => 'DEPOK'],
            ['id' => 240, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 33, 'name' => 'BANYUWANGI'],
            ['id' => 241, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 33, 'name' => 'PONOROGO'],
            ['id' => 253, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 49, 'name' => 'NTT'],
            ['id' => 255, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 31, 'name' => 'KUNINGAN'],
            ['id' => 256, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 30, 'name' => 'KARAWANG'],
            ['id' => 259, 'badan_usaha_id' => 4, 'division_id' => 7, 'region_id' => 50, 'name' => 'FEV-JABAR'],
            ['id' => 260, 'badan_usaha_id' => 4, 'division_id' => 7, 'region_id' => 52, 'name' => 'FEV-JATENG'],
            ['id' => 261, 'badan_usaha_id' => 4, 'division_id' => 7, 'region_id' => 60, 'name' => 'FEV-TANGBANTEN'],
            ['id' => 262, 'badan_usaha_id' => 4, 'division_id' => 7, 'region_id' => 55, 'name' => 'FEV-SUMATERA'],
            ['id' => 279, 'badan_usaha_id' => 4, 'division_id' => 7, 'region_id' => 58, 'name' => 'FEV-SULAWESI'],
            ['id' => 280, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 28, 'name' => 'TANGERANG'],
            ['id' => 281, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 61, 'name' => 'KABUPATENTANGERANG'],
            ['id' => 282, 'badan_usaha_id' => 2, 'division_id' => 5, 'region_id' => 61, 'name' => 'TANGERANGKOTA'],
            ['id' => 283, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 61, 'name' => 'TANGERANGKABUPATEN'],
            ['id' => 284, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 30, 'name' => 'KUNINGAN&MAJALENGKA'],
            ['id' => 285, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 29, 'name' => 'BEKASIKOTA'],
            ['id' => 286, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 28, 'name' => 'JABO'],
            ['id' => 287, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 63, 'name' => 'ZTESLO1'],
            ['id' => 288, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 64, 'name' => 'ZTESMG1'],
            ['id' => 289, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 64, 'name' => 'ZTESMG2'],
            ['id' => 290, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 66, 'name' => 'ZTEPWT1'],
            ['id' => 291, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 67, 'name' => 'ZTEJGJ1'],
            ['id' => 292, 'badan_usaha_id' => 2, 'division_id' => 4, 'region_id' => 16, 'name' => 'SMGASC1'],
            ['id' => 293, 'badan_usaha_id' => 2, 'division_id' => 4, 'region_id' => 16, 'name' => 'SMGASC2'],
            ['id' => 294, 'badan_usaha_id' => 2, 'division_id' => 4, 'region_id' => 16, 'name' => 'SMGTELE1'],
            ['id' => 295, 'badan_usaha_id' => 2, 'division_id' => 4, 'region_id' => 23, 'name' => 'BDGASC1'],
            ['id' => 296, 'badan_usaha_id' => 2, 'division_id' => 4, 'region_id' => 23, 'name' => 'BDGASC2'],
            ['id' => 297, 'badan_usaha_id' => 2, 'division_id' => 4, 'region_id' => 13, 'name' => 'CRBASC1'],
            ['id' => 298, 'badan_usaha_id' => 2, 'division_id' => 4, 'region_id' => 13, 'name' => 'CRBASC2'],
            ['id' => 299, 'badan_usaha_id' => 2, 'division_id' => 4, 'region_id' => 22, 'name' => 'JGJASC1'],
            ['id' => 300, 'badan_usaha_id' => 2, 'division_id' => 4, 'region_id' => 22, 'name' => 'JGJTELE1'],
            ['id' => 301, 'badan_usaha_id' => 2, 'division_id' => 4, 'region_id' => 24, 'name' => 'KRWASC1'],
            ['id' => 302, 'badan_usaha_id' => 2, 'division_id' => 4, 'region_id' => 24, 'name' => 'KRWASC2'],
            ['id' => 303, 'badan_usaha_id' => 2, 'division_id' => 4, 'region_id' => 24, 'name' => 'KRWASC3'],
            ['id' => 304, 'badan_usaha_id' => 2, 'division_id' => 4, 'region_id' => 26, 'name' => 'PWTASC1'],
            ['id' => 305, 'badan_usaha_id' => 2, 'division_id' => 4, 'region_id' => 26, 'name' => 'PWTTELE1'],
            ['id' => 306, 'badan_usaha_id' => 2, 'division_id' => 4, 'region_id' => 21, 'name' => 'SLOASC1'],
            ['id' => 307, 'badan_usaha_id' => 2, 'division_id' => 4, 'region_id' => 21, 'name' => 'SLOTELE1'],
            ['id' => 308, 'badan_usaha_id' => 2, 'division_id' => 4, 'region_id' => 27, 'name' => 'TSKASC1'],
            ['id' => 309, 'badan_usaha_id' => 2, 'division_id' => 4, 'region_id' => 27, 'name' => 'TSKASC2'],
            ['id' => 310, 'badan_usaha_id' => 2, 'division_id' => 4, 'region_id' => 14, 'name' => 'TGLASC1'],
            ['id' => 311, 'badan_usaha_id' => 2, 'division_id' => 4, 'region_id' => 14, 'name' => 'TGLTELE1'],
            ['id' => 312, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 68, 'name' => 'ZTETGL1'],
            ['id' => 314, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 31, 'name' => 'BEKASIO'],
            ['id' => 315, 'badan_usaha_id' => 2, 'division_id' => 4, 'region_id' => 24, 'name' => 'KRWASC4'],
            ['id' => 316, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 28, 'name' => 'JAKARTA'],
            ['id' => 317, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 67, 'name' => 'ZTEJGJ2'],
            ['id' => 319, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 31, 'name' => 'CIREBONO'],
            ['id' => 320, 'badan_usaha_id' => 5, 'division_id' => 9, 'region_id' => 69, 'name' => 'JAWATIMUR1'],
            ['id' => 321, 'badan_usaha_id' => 5, 'division_id' => 9, 'region_id' => 69, 'name' => 'JAWATIMUR2'],
            ['id' => 322, 'badan_usaha_id' => 5, 'division_id' => 9, 'region_id' => 69, 'name' => 'JAWATIMUR3'],
            ['id' => 323, 'badan_usaha_id' => 5, 'division_id' => 9, 'region_id' => 69, 'name' => 'JAWATIMUR4'],
            ['id' => 324, 'badan_usaha_id' => 5, 'division_id' => 9, 'region_id' => 70, 'name' => 'LAMPUNG'],
            ['id' => 325, 'badan_usaha_id' => 5, 'division_id' => 9, 'region_id' => 71, 'name' => 'RIAU'],
            ['id' => 326, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 88, 'name' => 'RIAU1'],
            ['id' => 327, 'badan_usaha_id' => 5, 'division_id' => 9, 'region_id' => 71, 'name' => 'ROKANHULU(ROHUL)'],
            ['id' => 328, 'badan_usaha_id' => 5, 'division_id' => 9, 'region_id' => 71, 'name' => 'INDRAGIRIHILIR'],
            ['id' => 329, 'badan_usaha_id' => 5, 'division_id' => 9, 'region_id' => 71, 'name' => 'DURI-DUMAI'],
            ['id' => 330, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 88, 'name' => 'RIAU2'],
            ['id' => 331, 'badan_usaha_id' => 5, 'division_id' => 9, 'region_id' => 71, 'name' => 'PELALAWAN'],
            ['id' => 332, 'badan_usaha_id' => 5, 'division_id' => 9, 'region_id' => 71, 'name' => 'SIAK-PERAWANG-BENGKALIS'],
            ['id' => 333, 'badan_usaha_id' => 5, 'division_id' => 9, 'region_id' => 71, 'name' => 'INHU'],
            ['id' => 334, 'badan_usaha_id' => 5, 'division_id' => 9, 'region_id' => 73, 'name' => 'SUMBAR1(PADANG)'],
            ['id' => 335, 'badan_usaha_id' => 5, 'division_id' => 9, 'region_id' => 73, 'name' => 'SUMBAR2(PARIAMAN)'],
            ['id' => 336, 'badan_usaha_id' => 5, 'division_id' => 9, 'region_id' => 73, 'name' => 'SUMBAR3(BUKITTINGGI)'],
            ['id' => 337, 'badan_usaha_id' => 5, 'division_id' => 9, 'region_id' => 73, 'name' => 'SUMBAR4(SOLOK)'],
            ['id' => 338, 'badan_usaha_id' => 5, 'division_id' => 9, 'region_id' => 74, 'name' => 'SUMSEL'],
            ['id' => 339, 'badan_usaha_id' => 5, 'division_id' => 9, 'region_id' => 74, 'name' => 'BENGKULU'],
            ['id' => 340, 'badan_usaha_id' => 5, 'division_id' => 9, 'region_id' => 74, 'name' => 'PALEMBANG'],
        ];

        // Insert first batch
        foreach (array_chunk($clusters, 50) as $batch) {
            foreach ($batch as $cluster) {
                Cluster::create($cluster);
            }
        }

        // Continue with remaining data
        $remainingClusters = [
            ['id' => 342, 'badan_usaha_id' => 5, 'division_id' => 9, 'region_id' => 75, 'name' => 'BKL'],
            ['id' => 343, 'badan_usaha_id' => 5, 'division_id' => 9, 'region_id' => 76, 'name' => 'BANGKABELITUNG'],
            ['id' => 344, 'badan_usaha_id' => 5, 'division_id' => 9, 'region_id' => 70, 'name' => 'SUMATERABARAT'],
            ['id' => 345, 'badan_usaha_id' => 2, 'division_id' => 4, 'region_id' => 23, 'name' => 'BDGASC3'],
            ['id' => 346, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 64, 'name' => 'ZTESMG3'],
            ['id' => 347, 'badan_usaha_id' => 2, 'division_id' => 4, 'region_id' => 27, 'name' => 'TSKASC3'],
            ['id' => 348, 'badan_usaha_id' => 2, 'division_id' => 4, 'region_id' => 16, 'name' => 'SMGTELE2'],
            ['id' => 349, 'badan_usaha_id' => 2, 'division_id' => 4, 'region_id' => 22, 'name' => 'JGJASC2'],
            ['id' => 350, 'badan_usaha_id' => 2, 'division_id' => 4, 'region_id' => 24, 'name' => 'KRWASC5'],
            ['id' => 351, 'badan_usaha_id' => 2, 'division_id' => 4, 'region_id' => 22, 'name' => 'JGJASC3'],
            ['id' => 352, 'badan_usaha_id' => 2, 'division_id' => 4, 'region_id' => 16, 'name' => 'SMGTELE3'],
            ['id' => 353, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 64, 'name' => 'SEMARANG-KENDAL'],
            ['id' => 354, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 66, 'name' => 'ZTEPWT2'],
            ['id' => 356, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 63, 'name' => 'ZTESLO2'],
            ['id' => 357, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 68, 'name' => 'ZTETGL2'],
            ['id' => 365, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 77, 'name' => 'ZTEBKS'],
            ['id' => 366, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 78, 'name' => 'SURABAYAINNER'],
            ['id' => 368, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 78, 'name' => 'SIDOARJO1'],
            ['id' => 369, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 78, 'name' => 'MOJOKERTO-JOMBANG'],
            ['id' => 370, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 78, 'name' => 'KEDIRI'],
            ['id' => 371, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 78, 'name' => 'MADURA'],
            ['id' => 372, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 62, 'name' => 'PASURUAN-PROBOLINGGO'],
            ['id' => 374, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 79, 'name' => 'MALANG1'],
            ['id' => 375, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 79, 'name' => 'BLITAR'],
            ['id' => 376, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 80, 'name' => 'JEMBER1'],
            ['id' => 377, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 80, 'name' => 'SITUBONDO-BONDOWOSO'],
            ['id' => 378, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 81, 'name' => 'BOJONEGORO-TUBAN'],
            ['id' => 379, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 81, 'name' => 'PONOROGO-PACIITAN'],
            ['id' => 380, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 80, 'name' => 'LUMAJANG'],
            ['id' => 381, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 81, 'name' => 'GRESIK1'],
            ['id' => 382, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 81, 'name' => 'NGAWI-MADIUN-NGANJUK'],
            ['id' => 383, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 82, 'name' => 'TAKENGON'],
            ['id' => 384, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 82, 'name' => 'BANDAACEH'],
            ['id' => 385, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 82, 'name' => 'MATANGBIREUN'],
            ['id' => 386, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 82, 'name' => 'LHOKSEUMAWE'],
            ['id' => 387, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 82, 'name' => 'MELABOH,SUBULUSSALAM'],
            ['id' => 388, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 82, 'name' => 'ACEHTIMUR'],
            ['id' => 389, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 83, 'name' => 'BANGKA'],
            ['id' => 391, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 85, 'name' => 'BENGKULU2'],
            ['id' => 392, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 85, 'name' => 'BENGKULU1'],
            ['id' => 393, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 85, 'name' => 'BENGKULU3'],
            ['id' => 394, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 86, 'name' => 'JAMBI1'],
            ['id' => 395, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 86, 'name' => 'JAMBI2'],
            ['id' => 396, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 86, 'name' => 'JAMBI3'],
            ['id' => 397, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 86, 'name' => 'JAMBI4'],
            ['id' => 398, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 88, 'name' => 'RIAU3'],
            ['id' => 399, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 88, 'name' => 'RIAU4'],
            ['id' => 400, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 88, 'name' => 'RIAU5'],
            ['id' => 401, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 88, 'name' => 'RIAU6'],
            ['id' => 402, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 88, 'name' => 'RIAU7'],
            ['id' => 403, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 88, 'name' => 'RIAU8'],
            ['id' => 404, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 89, 'name' => 'SUMBAR1'],
            ['id' => 405, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 89, 'name' => 'SUMBAR2'],
            ['id' => 406, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 89, 'name' => 'SUMBAR3'],
            ['id' => 407, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 89, 'name' => 'SUMBAR4'],
            ['id' => 408, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 93, 'name' => 'SUMSEL1'],
            ['id' => 409, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 93, 'name' => 'SUMSEL2'],
            ['id' => 410, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 93, 'name' => 'SUMSEL3'],
            ['id' => 411, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 93, 'name' => 'SUMSEL4'],
            ['id' => 412, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 93, 'name' => 'SUMSEL5'],
            ['id' => 413, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 93, 'name' => 'SUMSEL6'],
            ['id' => 414, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 99, 'name' => 'RANTAU,LABUANBATU'],
            ['id' => 415, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 99, 'name' => 'SIDEMPUAN-SIBOLGA'],
            ['id' => 416, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 99, 'name' => 'LABUHANBATU,PASAHAN'],
            ['id' => 417, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 99, 'name' => 'MEDANKOTA'],
            ['id' => 418, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 99, 'name' => 'DELISERDANG1'],
            ['id' => 419, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 99, 'name' => 'DELISERDANG2'],
            ['id' => 420, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 99, 'name' => 'KOTAMEDAN'],
            ['id' => 421, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 99, 'name' => 'BINJAILANGKAT'],
            ['id' => 422, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 99, 'name' => 'SIANTARTEBINGTINGGI'],
            ['id' => 423, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 99, 'name' => 'KARODAIRI'],
            ['id' => 424, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 109, 'name' => 'JABO1'],
            ['id' => 425, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 110, 'name' => 'JABAR1A'],
            ['id' => 426, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 110, 'name' => 'JABAR1B'],
            ['id' => 427, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 110, 'name' => 'JABAR1C'],
            ['id' => 428, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 111, 'name' => 'JABAR2A'],
            ['id' => 429, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 111, 'name' => 'JABAR2B'],
            ['id' => 430, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 112, 'name' => 'JABAR3A'],
            ['id' => 431, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 113, 'name' => 'JABAR4A'],
            ['id' => 432, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 113, 'name' => 'JABAR4B'],
            ['id' => 433, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 114, 'name' => 'JABAR5A'],
            ['id' => 434, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 77, 'name' => 'BEKASIINNER'],
            ['id' => 435, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 77, 'name' => 'BEKASIOUTER'],
            ['id' => 436, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 77, 'name' => 'CIKARANG-ZTE'],
            ['id' => 437, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 115, 'name' => 'KAB.BOGOR'],
            ['id' => 438, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 115, 'name' => 'KOTABOGOR'],
            ['id' => 439, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 115, 'name' => 'JAKARTATIMUR'],
            ['id' => 440, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 115, 'name' => 'JAKARTAUTARA'],
            ['id' => 441, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 87, 'name' => 'LAMPUNG1'],
            ['id' => 442, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 87, 'name' => 'LAMPUNG2'],
            ['id' => 443, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 87, 'name' => 'LAMPUNG3'],
            ['id' => 444, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 87, 'name' => 'LAMPUNG4'],
            ['id' => 445, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 112, 'name' => 'JABAR3B'],
            ['id' => 447, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 78, 'name' => 'SIMOJOM'],
            ['id' => 448, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 78, 'name' => 'KEDIRI-NGANJUK-JOMBANG'],
            ['id' => 449, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 81, 'name' => 'NGAWI-MADIUN'],
            ['id' => 450, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 81, 'name' => 'NGANJUK'],
            ['id' => 451, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 114, 'name' => 'JABAR5B'],
            ['id' => 452, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 87, 'name' => 'LAMPUNG5'],
            ['id' => 453, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 4498, 'name' => 'KEP. RIAU01'],
            ['id' => 454, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 4498, 'name' => 'KEP. RIAU02'],
            ['id' => 455, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 115, 'name' => 'BANTEN'],
            ['id' => 456, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 112, 'name' => 'JABAR3C'],
            ['id' => 457, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 4498, 'name' => 'KEP. RIAU03'],
            ['id' => 458, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 113, 'name' => 'JABAR4C'],
            ['id' => 459, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 64, 'name' => 'SEMARANGTIMUR2'],
            ['id' => 461, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 66, 'name' => 'PURWOKERTO-TEGAL'],
            ['id' => 465, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 68, 'name' => 'PEKALONGAN-BATANG'],
            ['id' => 466, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 114, 'name' => 'JABAR5C'],
            ['id' => 467, 'badan_usaha_id' => 2, 'division_id' => 2, 'region_id' => 31, 'name' => 'CIANJUR-SUKABUMI'],
            ['id' => 468, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 85, 'name' => 'BENGKULU4'],
            ['id' => 469, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 83, 'name' => 'BELITUNG'],
            ['id' => 470, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 86, 'name' => 'JAMBI5'],
            ['id' => 471, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 89, 'name' => 'SUMBAR5'],
            ['id' => 472, 'badan_usaha_id' => 5, 'division_id' => 8, 'region_id' => 111, 'name' => 'JABAR2C'],
            ['id' => 473, 'badan_usaha_id' => 2, 'division_id' => 4, 'region_id' => 14, 'name' => 'FORTESTING'],
            ['id' => 474, 'badan_usaha_id' => 5, 'division_id' => 11, 'region_id' => 89, 'name' => 'SUMBAR6'],
            ['id' => 475, 'badan_usaha_id' => 2, 'division_id' => 4, 'region_id' => 14, 'name' => ''],
        ];

        foreach (array_chunk($remainingClusters, 50) as $batch) {
            foreach ($batch as $cluster) {
                Cluster::create($cluster);
            }
        }
    }
}
